
------------------- MODULE Constants -----------------------
\* NOTE: This file is automatically generated. See the project Makefile
EXTENDS Naturals

CONSTANT
  \* @type: Set(Int);
  Values

CInit0 == Values = 0..0
CInit2 == Values = 0..2
CInit4 == Values = 0..4
CInit6 == Values = 0..6
CInit8 == Values = 0..8
CInit10 == Values = 0..10
CInit12 == Values = 0..12
CInit14 == Values = 0..14

============================================================

