name: Benchmarks

# TODO Make this only run on certain branches/commits?
on: push

env:
  REPORT_BRANCH: report-${{ github.run_id }}

jobs:
  create-report-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git checkout -b $REPORT_BRANCH
      - run: git push -u origin $REPORT_BRANCH

  run-benchmarks:
    needs: create-report-branch
    strategy:
      matrix:
        version:
          - 0.7.0
          - 0.6.1
        strat:
          - 001indinv
          # FIXME
          # - 002bmc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: report-${{ github.run_id }}
      - run: make experiment-${{ matrix.strat }}-${{ matrix.version}}-serial
      - run: git config user.name github-ci
      - run: git config user.email todo@example.com
      - run: git commit . -m "Adding experiment results"
      - run: git push -u origin $REPORT_BRANCH

  make-report:
    needs: run-benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: report-${{ github.run_id }}
      - run: make reports-only
      - run: git config user.name github-ci
      - run: git config user.email todo@example.com
      - run: git commit . -m "Adding report"
      - run: git push -u origin $REPORT_BRANCH
